<?php

namespace AppBundle\Repository\User\Spouse;

/**
 * OccupationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccupationRepository extends \Doctrine\ORM\EntityRepository
{
}
