<?php

namespace AppBundle\Repository\User;

/**
 * SpouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpouseRepository extends \Doctrine\ORM\EntityRepository
{
}
